apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nars-api
  namespace: nars
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nars.dz
      secretName: nars-tls
  rules:
    - host: nars.dz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nars-api
                port:
                  number: 80
