apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nars
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
