apiVersion: v1
kind: Secret
metadata:
  name: nars-secrets
  namespace: nars
type: Opaque
stringData:
  # Update these values before deploying.
  postgres_password: "+Qwbl22+OVKlgjvqHK0CO8QeNRZhtTcd"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=nars_db;Username=postgres;Password=+Qwbl22+OVKlgjvqHK0CO8QeNRZhtTcd"
  Jwt__SecretKey: "Vui3wkPhhCJL5gnKr8gj8CQeAibRp1uPfEJIuLngdtxbhPoHCZ9/N9xSY1XJuOE3"
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: nars
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"https://index.docker.io/v1/":{"username":"zuhirbenslama","password":"change-me","auth":"<base64-encoded-username:password>"}}}
