/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/admin/overview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/wilaya/{wilayaId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          wilayaId: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/daira/{dairaId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          dairaId: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/authorized-signup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: {
          "X-Admin-Signup"?: string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthorizedAdminSignupRequest"]
          "text/json": components["schemas"]["AuthorizedAdminSignupRequest"]
          "application/*+json": components["schemas"]["AuthorizedAdminSignupRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Locked */
        423: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateAdminRequest"]
          "text/json": components["schemas"]["CreateAdminRequest"]
          "application/*+json": components["schemas"]["CreateAdminRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/users/{userId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateAdminRequest"]
          "text/json": components["schemas"]["UpdateAdminRequest"]
          "application/*+json": components["schemas"]["UpdateAdminRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/signup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Gone */
        410: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/signin": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignInRequest"]
          "text/json": components["schemas"]["SignInRequest"]
          "application/*+json": components["schemas"]["SignInRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/current_user": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/draft-features/segment": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": {
            /** Format: int32 */
            CommuneId?: number | string
            Tile?: components["schemas"]["IFormFile"]
            /** Format: double */
            MinLon?: number | string
            /** Format: double */
            MinLat?: number | string
            /** Format: double */
            MaxLon?: number | string
            /** Format: double */
            MaxLat?: number | string
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["SegmentSummaryResponse"]
            "application/json": components["schemas"]["SegmentSummaryResponse"]
            "text/json": components["schemas"]["SegmentSummaryResponse"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/draft-features": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          communeId?: number | string
          featureType?: string
          status?: string
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["PagedResponseOfAiDraftFeatureDto"]
            "application/json": components["schemas"]["PagedResponseOfAiDraftFeatureDto"]
            "text/json": components["schemas"]["PagedResponseOfAiDraftFeatureDto"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/draft-features/{id}/accept": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/draft-features/{id}/reject": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/feature-types": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/features/by-layer/{layerType}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          skip?: number | string
          take?: number | string
        }
        header?: never
        path: {
          layerType: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/features": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["FeatureSaveRequest"]
          "text/json": components["schemas"]["FeatureSaveRequest"]
          "application/*+json": components["schemas"]["FeatureSaveRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/features/clear": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["ClearFeaturesRequest"]
          "text/json": components["schemas"]["ClearFeaturesRequest"]
          "application/*+json": components["schemas"]["ClearFeaturesRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/features/stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/features/{featureId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          featureId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["FeatureUpdateRequest"]
          "text/json": components["schemas"]["FeatureUpdateRequest"]
          "application/*+json": components["schemas"]["FeatureUpdateRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          featureId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/field/features": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          type?: string
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/field/inspect": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["FieldInspectRequest"]
          "text/json": components["schemas"]["FieldInspectRequest"]
          "application/*+json": components["schemas"]["FieldInspectRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/field/inspections/{featureId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          skip?: number | string
          take?: number | string
        }
        header?: never
        path: {
          featureId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/field/entrance": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["FieldEntranceCreateRequest"]
          "text/json": components["schemas"]["FieldEntranceCreateRequest"]
          "application/*+json": components["schemas"]["FieldEntranceCreateRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/wilayas": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          search?: string
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/dairas": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          wilaya_id?: number | string
          search?: string
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/communes": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          daira_id?: number | string
          search?: string
          skip?: number | string
          take?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/commune/{communeId}/boundary": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          communeId: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/commune/{communeId}/boundary-debug": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          communeId: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/logs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["LogBatch"]
          "application/*+json": components["schemas"]["LogBatch"]
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/road-side": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["RoadSideRequest"]
          "text/json": components["schemas"]["RoadSideRequest"]
          "application/*+json": components["schemas"]["RoadSideRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/areas/scattered-status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/areas/refresh-scattered": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/user/profile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateUserRequest"]
          "text/json": components["schemas"]["UpdateUserRequest"]
          "application/*+json": components["schemas"]["UpdateUserRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/validate/area/main-urban-exists": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/validate/road": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["ValidateRoadRequest"]
          "text/json": components["schemas"]["ValidateRoadRequest"]
          "application/*+json": components["schemas"]["ValidateRoadRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/validate/district": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["ValidateDistrictRequest"]
          "text/json": components["schemas"]["ValidateDistrictRequest"]
          "application/*+json": components["schemas"]["ValidateDistrictRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/validate/districts/coverage": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AiDraftFeatureDto: {
      /** Format: uuid */
      id: string
      featureType: string
      geometryGeoJson: string
      /** Format: double */
      confidence: number | string
      status: string
      /** Format: date-time */
      createdAt: string
    }
    AuthorizedAdminSignupRequest: {
      admin_username: string
      admin_password: string
      name: string
      email: string
      phone: string
      username: string
      password: string
      role: string
      /** Format: int32 */
      commune_id: null | number | string
      /** Format: int32 */
      daira_id: null | number | string
      /** Format: int32 */
      wilaya_id: null | number | string
    }
    ClearFeaturesRequest: {
      confirm: boolean
    }
    CoordDto: {
      /** Format: double */
      lat: number | string
      /** Format: double */
      lng: number | string
    }
    CreateAdminRequest: {
      name: string
      email: string
      phone: string
      username: string
      password: string
      role: string
      /** Format: int32 */
      commune_id: null | number | string
      /** Format: int32 */
      daira_id: null | number | string
      /** Format: int32 */
      wilaya_id: null | number | string
    }
    FeatureSaveRequest: {
      type: string
      layer: string
      label: string
      data: components["schemas"]["JsonElement"]
    }
    FeatureUpdateRequest: {
      label: null | string
      data: null | components["schemas"]["JsonElement"]
    }
    FieldEntranceCreateRequest: {
      road_id: string
      data: components["schemas"]["JsonNode"]
      label: null | string
    }
    FieldInspectRequest: {
      feature_id: string
      type: string
      data: components["schemas"]["JsonNode"]
      status: string
    }
    /** Format: binary */
    IFormFile: string
    JsonElement: unknown
    JsonNode: unknown
    LogBatch: {
      logs: components["schemas"]["LogEntry"][]
    }
    LogEntry: {
      level: null | string
      code: null | string
      message: string
      context: null | string
      url: null | string
      method: null | string
    }
    PagedResponseOfAiDraftFeatureDto: {
      items: components["schemas"]["AiDraftFeatureDto"][]
      /** Format: int32 */
      total: number | string
      /** Format: int32 */
      skip: number | string
      /** Format: int32 */
      take: number | string
      /** @default true */
      success: boolean
    }
    ProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
    }
    RoadSideRequest: {
      /** Format: uuid */
      roadId: string
      /** Format: double */
      lat: number | string
      /** Format: double */
      lng: number | string
    }
    SegmentSummaryResponse: {
      /** Format: int32 */
      buildingCount: number | string
      draftIds: string[]
    }
    SignInRequest: {
      username: string
      password: string
    }
    UpdateAdminRequest: {
      name: null | string
      email: null | string
      phone: null | string
      role: null | string
      /** Format: int32 */
      commune_id: null | number | string
      /** Format: int32 */
      daira_id: null | number | string
      /** Format: int32 */
      wilaya_id: null | number | string
      password: null | string
    }
    UpdateUserRequest: {
      username: null | string
      email: null | string
      current_password: null | string
      password: null | string
    }
    ValidateDistrictRequest: {
      coordinates: components["schemas"]["CoordDto"][]
      districtTypeKey: null | string
    }
    ValidateRoadRequest: {
      coordinates: components["schemas"]["CoordDto"][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
