apiVersion: v1
kind: Service
metadata:
  name: otel-collector-metrics
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: metrics
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: prometheus
      port: 8889
      targetPort: 8889
      protocol: TCP
