---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-metrics
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: prometheus-exporter
      port: 8889
      targetPort: 8889
      protocol: TCP
  selector:
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
