apiVersion: v1
kind: ResourceQuota
metadata:
  name: nars-quota
  namespace: nars
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: 3
    services: 8
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nars-limits
  namespace: nars
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
