---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nars-api
  namespace: nars
  labels:
    app.kubernetes.io/name: nars-api
    app.kubernetes.io/component: api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nars-frontend
  namespace: nars
  labels:
    app.kubernetes.io/name: nars-frontend
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nars-roads
  namespace: nars
  labels:
    app.kubernetes.io/name: nars-roads
    app.kubernetes.io/component: segmentation
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgis
  namespace: nars
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/component: database
automountServiceAccountToken: false
