apiVersion: v1
kind: ServiceAccount
metadata:
  name: nars-api
  namespace: nars
  labels:
    app.kubernetes.io/name: nars-api
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nars-frontend
  namespace: nars
  labels:
    app.kubernetes.io/name: nars-frontend
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgis
  namespace: nars
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/component: database
