-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;


CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public.areas
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT areas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.city_centers
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'city_center'::character varying,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL DEFAULT 'City Center'::character varying,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT city_centers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.communes
(
    commune_id integer NOT NULL,
    daira_id integer NOT NULL,
    commune_code integer,
    commune_ar character varying COLLATE pg_catalog."default" NOT NULL,
    commune_fr character varying COLLATE pg_catalog."default" NOT NULL,
    commune_latitude double precision,
    commune_longitude double precision,
    commune_name character varying COLLATE pg_catalog."default",
    CONSTRAINT communes_pkey PRIMARY KEY (commune_id)
);

CREATE TABLE IF NOT EXISTS public.communes_boundaries
(
    commune_id integer NOT NULL,
    geometry geometry NOT NULL,
    CONSTRAINT communes_boundaries_pkey1 PRIMARY KEY (commune_id)
);

CREATE TABLE IF NOT EXISTS public.dairas
(
    daira_id integer NOT NULL,
    wilaya_id integer NOT NULL,
    daira_ar character varying COLLATE pg_catalog."default" NOT NULL,
    daira_fr character varying COLLATE pg_catalog."default" NOT NULL,
    daira_latitude double precision,
    daira_longitude double precision,
    daira_name character varying COLLATE pg_catalog."default",
    CONSTRAINT dairas_pkey PRIMARY KEY (daira_id)
);

CREATE TABLE IF NOT EXISTS public.districts
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT districts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.feature_registry
(
    feature_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    CONSTRAINT feature_registry_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.house_entrances
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    road_id uuid,
    CONSTRAINT house_entrances_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.naming_panels
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'naming_panel'::character varying,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT naming_panels_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.public_buildings
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public_building'::character varying,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT public_buildings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.public_spaces
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT public_spaces_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    token_hash character varying(64) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    revoked boolean NOT NULL DEFAULT false,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roads
(
    layer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    label character varying(500) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT roads_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    commune_id integer,
    created_at timestamp without time zone NOT NULL,
    failed_login_attempts integer DEFAULT 0,
    locked_until timestamp with time zone,
    id uuid NOT NULL,
    daira_id integer,
    wilaya_id integer,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'commune_user'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.wilayas
(
    wilaya_id integer NOT NULL,
    wilaya_ar character varying COLLATE pg_catalog."default" NOT NULL,
    wilaya_fr character varying COLLATE pg_catalog."default" NOT NULL,
    wilaya_latitude double precision,
    wilaya_longitude double precision,
    CONSTRAINT wilayas_pkey PRIMARY KEY (wilaya_id)
);

ALTER TABLE IF EXISTS public.areas
    ADD CONSTRAINT areas_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_areas_user_id
    ON public.areas(user_id);


ALTER TABLE IF EXISTS public.city_centers
    ADD CONSTRAINT city_centers_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_city_centers_user_id
    ON public.city_centers(user_id);


ALTER TABLE IF EXISTS public.districts
    ADD CONSTRAINT districts_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_districts_user_id
    ON public.districts(user_id);


ALTER TABLE IF EXISTS public.house_entrances
    ADD CONSTRAINT house_entrances_road_fk FOREIGN KEY (road_id)
    REFERENCES public.roads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_house_entrances_road_id
    ON public.house_entrances(road_id);


ALTER TABLE IF EXISTS public.house_entrances
    ADD CONSTRAINT house_entrances_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_house_entrances_user_id
    ON public.house_entrances(user_id);


ALTER TABLE IF EXISTS public.naming_panels
    ADD CONSTRAINT naming_panels_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_naming_panels_user_id
    ON public.naming_panels(user_id);


ALTER TABLE IF EXISTS public.public_buildings
    ADD CONSTRAINT public_buildings_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_public_buildings_user_id
    ON public.public_buildings(user_id);


ALTER TABLE IF EXISTS public.public_spaces
    ADD CONSTRAINT public_spaces_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_public_spaces_user_id
    ON public.public_spaces(user_id);


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
    ON public.refresh_tokens(user_id);


ALTER TABLE IF EXISTS public.roads
    ADD CONSTRAINT roads_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_roads_user_id
    ON public.roads(user_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_daira_fk FOREIGN KEY (daira_id)
    REFERENCES public.dairas (daira_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_users_daira_id
    ON public.users(daira_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_wilaya_fk FOREIGN KEY (wilaya_id)
    REFERENCES public.wilayas (wilaya_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_users_wilaya_id
    ON public.users(wilaya_id);

-- Record the initial EF Core migration as already applied
-- (the schema above was generated from this migration).
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510191030_AddErrorLogs', '10.0.7')
ON CONFLICT DO NOTHING;

END;